### ISSUE TITLE
Метод `public int sumGenre(String genre)` в классе `Player.java` всегда возвращает ноль. 

### ISSUE THREAD

**Issue by ivan89898** [KattyKukh/TeamProject-Games#6]
# Описание
Метод `public int sumGenre(String genre)` в классе `Player.java` всегда возвращает ноль. 

# Локация дефекта
https://github.com/KattyKukh/TeamProject-Games/blob/54b0193045910c2f11ec5105ea96921e396be411/src/main/java/ru/netology/Player.java#L45-L55
# Шаги воспроизведения
1. Открыть [Player.java](https://github.com/KattyKukh/TeamProject-Games/blob/master/src/main/java/ru/netology/Player.java), [Game.java](https://github.com/KattyKukh/TeamProject-Games/blob/master/src/main/java/ru/netology/Game.java), [GameStore.java](https://github.com/KattyKukh/TeamProject-Games/blob/master/src/main/java/ru/netology/GameStore.java), [PlayerTest.java](https://github.com/KattyKukh/TeamProject-Games/blob/master/src/test/java/ru/netology/PlayerTest.java), [pom.xml](https://github.com/KattyKukh/TeamProject-Games/blob/master/pom.xml) в IDEA
3. Запустить тест ` @Test
    public void shouldSumGenreIfOneGame()`
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест проходит
*Фактический результат:* Тест падает

# Скриншот
![Снимок экрана (9)](https://user-images.githubusercontent.com/103887530/179404014-207494c0-24ad-4e4e-bffa-32195eecaf4d.png)

# Окружение
* **Операционная система:** Windows11
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** Open JDK 11

**Comment by KattyKukh** [comment]
К дефекту приводило отсутствие добавления времени в методе play(). Метод play() исправлен в коммите Fixed #5.
